[programs.localnet]
anchor-dex = "3aDAMELieXNz932mDFcrmicrvSVAVhmmigFixd6PngtN"

[registry]
url = "https://api.apr.dev"
[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
slots_per_epoch = "33"
ticks_per_slot = 7
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
